//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAPPCT.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogicModuleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogicModuleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VAPPCT.Data.LogicModuleMessages", typeof(LogicModuleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute action: .
        /// </summary>
        internal static string ERROR_EXE_EXP {
            get {
                return ResourceManager.GetString("ERROR_EXE_EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate logic: .
        /// </summary>
        internal static string ERROR_LOGIC {
            get {
                return ResourceManager.GetString("ERROR_LOGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse place holder: .
        /// </summary>
        internal static string ERROR_PARSE {
            get {
                return ResourceManager.GetString("ERROR_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown temporal state tim period time unit..
        /// </summary>
        internal static string ERROR_PARSE_TSTIMEPERIODDATE {
            get {
                return ResourceManager.GetString("ERROR_PARSE_TSTIMEPERIODDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert run logic parameters..
        /// </summary>
        internal static string ERROR_RUN_LOGIC {
            get {
                return ResourceManager.GetString("ERROR_RUN_LOGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action found: .
        /// </summary>
        internal static string ERROR_VALIDATE_ACTION {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of opening curly braces do not match the number of closing curly braces..
        /// </summary>
        internal static string ERROR_VALIDATE_CURLY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_CURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a period outside a set of curly braces..
        /// </summary>
        internal static string ERROR_VALIDATE_DOT {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a closing curly brace before an opening curly brace..
        /// </summary>
        internal static string ERROR_VALIDATE_ECURLY_OCURLY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_ECURLY_OCURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions may only contain the keyword &quot;else&quot; once..
        /// </summary>
        internal static string ERROR_VALIDATE_ELSE_DOUBLE {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_ELSE_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;else&quot; statement is null or empty..
        /// </summary>
        internal static string ERROR_VALIDATE_ELSE_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_ELSE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions must begin with the keyword &quot;if.&quot;.
        /// </summary>
        internal static string ERROR_VALIDATE_IF {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions may only contain the keyword &quot;if&quot; once..
        /// </summary>
        internal static string ERROR_VALIDATE_IF_DOUBLE {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_IF_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found the keyword &quot;else&quot; before the keyword &quot;then.&quot;.
        /// </summary>
        internal static string ERROR_VALIDATE_IF_ELSE_THEN {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_IF_ELSE_THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;if&quot; statement is null or empty..
        /// </summary>
        internal static string ERROR_VALIDATE_IF_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_IF_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a semicolon before the keyword &quot;then.&quot;.
        /// </summary>
        internal static string ERROR_VALIDATE_IF_SEMI_THEN {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_IF_SEMI_THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expression is null or empty..
        /// </summary>
        internal static string ERROR_VALIDATE_NULL {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found two opening curly braces before a closing curly brace..
        /// </summary>
        internal static string ERROR_VALIDATE_OCURLY_OCURLY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_OCURLY_OCURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action parameters not found..
        /// </summary>
        internal static string ERROR_VALIDATE_PARAM {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown placeholder found: .
        /// </summary>
        internal static string ERROR_VALIDATE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions must end with a semicolon..
        /// </summary>
        internal static string ERROR_VALIDATE_SEMI {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_SEMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions may only contain one semicolon..
        /// </summary>
        internal static string ERROR_VALIDATE_SEMI_DOUBLE {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_SEMI_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions must contain the keyword &quot;then.&quot;.
        /// </summary>
        internal static string ERROR_VALIDATE_THEN {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_THEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic expressions may only contain the keyword &quot;then&quot; once..
        /// </summary>
        internal static string ERROR_VALIDATE_THEN_DOUBLE {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_THEN_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;then&quot; statement is null or empty..
        /// </summary>
        internal static string ERROR_VALIDATE_THEN_EMPTY {
            get {
                return ResourceManager.GetString("ERROR_VALIDATE_THEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation successful..
        /// </summary>
        internal static string SUCCESS_VALIDATE {
            get {
                return ResourceManager.GetString("SUCCESS_VALIDATE", resourceCulture);
            }
        }
    }
}
